#pragma once
#include <Arduino.h>

static const char ARCADE_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name="theme-color" content="#090b12"><title>LED Arcade</title><style>
:root{--accent:#6d7cff;--bg:#090b12;--panel:#141827;--text:#f7f8ff;--muted:#9ca6c7}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at top,#202746,var(--bg) 55%);color:var(--text);font-family:system-ui,-apple-system,sans-serif;overscroll-behavior:none;touch-action:manipulation}body{display:flex;justify-content:center}.app{width:min(100%,560px);min-height:100vh;padding:18px;display:flex;flex-direction:column}.top{display:flex;justify-content:space-between;align-items:center;gap:10px}.brand{font-weight:900;letter-spacing:.12em}.identity{display:flex;align-items:center;gap:8px;min-width:0}.dot{width:18px;height:18px;border-radius:50%;background:var(--accent);box-shadow:0 0 18px var(--accent)}.idtxt{font-size:12px;font-weight:900}.status{font-size:11px;color:var(--muted)}h1{font-size:34px;margin:30px 0 8px}p{color:var(--muted);margin:0 0 20px}.grid,.players{display:grid;gap:12px}.card,.button{border:1px solid #303854;background:linear-gradient(160deg,#1a2033,#101420);border-radius:18px;padding:18px;color:var(--text);box-shadow:0 12px 30px #0006}.card{text-align:left}.card strong{font-size:22px;display:block}.card span{color:var(--muted)}.button{width:100%;font-size:17px;font-weight:850;text-align:center;margin-top:12px}.primary{background:linear-gradient(135deg,var(--accent),#924cff);border:0}.danger{border-color:#763143;color:#ffb4c3}.mutedBtn{opacity:.8}.disabled{opacity:.38}.hidden{display:none!important}.score{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:13px 0}.cell{background:#111625;border:1px solid #2a3148;border-radius:12px;padding:8px 5px;text-align:center}.cell b{display:block;font-size:18px}.cell span{font-size:9px;color:var(--muted)}.player{display:flex;justify-content:space-between;padding:11px 13px;border-radius:13px;background:#151a2b}.tap{flex:1;min-height:58vh;display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:27px;background:linear-gradient(145deg,var(--accent),#2d3470);font-size:48px;font-weight:1000;user-select:none;-webkit-user-select:none}.tap small{font-size:16px;margin:7px}.count{font-size:84px;text-align:center;font-weight:1000;margin:auto}.winner{text-align:center;margin:auto}.boss{flex:1;min-height:58vh;display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:27px;background:radial-gradient(circle,#701515,#240b12 65%);user-select:none;-webkit-user-select:none}.boss h1{margin:0;font-size:42px}.hp{width:86%;height:22px;border:2px solid #fff;border-radius:999px;overflow:hidden;margin:18px 0}.hp>div{height:100%;background:linear-gradient(90deg,#ffde3b,#ff433b);width:100%}.bossTap{font-size:44px;font-weight:1000}.bonus{color:#ffd84a;font-weight:900}.session{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.footer{margin-top:auto;padding-top:14px;text-align:center;color:var(--muted);font-size:11px}
</style></head><body><main class="app"><div class="top"><div class="brand">LED ARCADE</div><div class="identity"><span id="dot" class="dot hidden"></span><span id="idtxt" class="idtxt">İZLEYİCİ</span></div><div id="status" class="status">Bağlanıyor…</div></div><div id="score" class="score hidden"><div class="cell"><b id="points">0</b><span>SKOR</span></div><div class="cell"><b id="round">0/2</b><span>RAUND</span></div><div class="cell"><b id="streak">0</b><span>SERİ</span></div><div class="cell"><b id="power">—</b><span>POWER</span></div></div>
<section id="platform"><h1>Platform seç</h1><div class="grid"><button class="card disabled"><strong>1D Arena</strong><span>Yakında</span></button><button id="matrixBtn" class="card"><strong>8×32 Arena</strong><span>Yarış ve takım oyunları</span></button></div></section>
<section id="games" class="hidden"><h1>Oyun seç</h1><button id="derbyBtn" class="card"><strong>Pixel Derby</strong><span>Yarış, turbo ve King Boss</span></button></section>
<section id="lobby" class="hidden"><h1>Pixel Derby</h1><p id="roleText"></p><div id="players" class="players"></div><button id="readyBtn" class="button">HAZIRIM</button><button id="startBtn" class="button primary hidden">YARIŞI BAŞLAT</button></section>
<section id="countdown" class="hidden count">3</section>
<section id="race" class="hidden tap"><small id="raceId">OYUNCU</small><small id="raceStats">Sıra: —</small><span>TAP!</span><small id="turboText" class="bonus"></small></section>
<section id="result" class="hidden winner"><h1 id="winnerText">Kazanan</h1><p id="scoreText"></p><button id="rematchBtn" class="button primary">DEVAM ET</button></section>
<section id="boss" class="hidden boss"><h1 id="bossTitle">KING BOSS</h1><p id="bossRole"></p><div class="hp"><div id="hpFill"></div></div><div id="bossStats"></div><div id="bossAction" class="bossTap">SALDIR!</div><small id="bossHint">Telefonun tamamına dokun</small></section>
<section id="boss_result" class="hidden winner"><h1 id="bossResultText">BOSS</h1><p id="bossResultScore"></p><button id="bossContinueBtn" class="button primary">LOBBY'YE DÖN</button></section>
<div id="joinBox" class="hidden"><button id="joinBtn" class="button primary">OYUNA KATIL</button></div><div id="sessionBox" class="session hidden"><button id="waitBtn" class="button mutedBtn">BEKLEMEYE GEÇ</button><button id="leaveBtn" class="button danger">OYUNDAN AYRIL</button></div><div class="footer">Bekleme modu slotunu ve skorunu korur. Ayrılma slotu hemen boşaltır.</div></main><script>
const $=id=>document.getElementById(id),views=["platform","games","lobby","countdown","race","result","boss","boss_result"];const colors=["#3b82f6","#ff3b9d","#35d07f","#ffd84a","#32d6e8","#ff8a35","#a970ff","#ffffff"],names=["MAVİ","PEMBE","YEŞİL","SARI","TURKUAZ","TURUNCU","MOR","BEYAZ"];let ws,me=-1,state=null,ready=false,cid=localStorage.getItem("ledArcadeCid");if(!cid){cid=crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();localStorage.setItem("ledArcadeCid",cid)}let rt,ht,lastTap=0;
function show(v){views.forEach(x=>$(x).classList.toggle("hidden",x!==v))}function send(m){if(ws?.readyState===1)ws.send(m)}function connect(){clearTimeout(rt);ws=new WebSocket(`ws://${location.hostname}:81/`);ws.onopen=()=>{$("status").textContent="Bağlandı";send("HELLO|"+cid);clearInterval(ht);ht=setInterval(()=>send("PING"),5000)};ws.onclose=()=>{clearInterval(ht);$("status").textContent="Yeniden bağlanıyor…";rt=setTimeout(connect,2000)};ws.onerror=()=>ws.close();ws.onmessage=e=>{try{render(JSON.parse(e.data))}catch(_){}}}
function mine(s){return s.players.find(p=>p.slot===me)}function rank(s){const a=s.players.filter(p=>p.connected&&!p.waiting).sort((x,y)=>y.position-x.position||x.slot-y.slot);return a.findIndex(p=>p.slot===me)+1}function renderIdentity(p){const active=!!p;$("dot").classList.toggle("hidden",!active);$("idtxt").textContent=active?`${names[p.slot]} · OYUNCU ${p.slot+1}${p.waiting?" · BEKLEMEDE":""}`:"İZLEYİCİ";document.documentElement.style.setProperty("--accent",active?colors[p.slot]:"#6d7cff");$("sessionBox").classList.toggle("hidden",!active);$("joinBox").classList.toggle("hidden",active);if(active)$("waitBtn").textContent=p.waiting?"OYUNA DÖN":"BEKLEMEYE GEÇ"}
function renderScore(s,p){$("score").classList.toggle("hidden",!p);if(!p)return;$("points").textContent=p.points;$("round").textContent=`${p.score}/${s.matchWinScore}`;$("streak").textContent=p.streak;$("power").textContent=p.turboTaps?`TURBO ×${p.turboTaps}`:(s.stage==="boss"?(p.slot===s.bossSlot?`${p.bossEnergy}/12`:`${p.bossDamage} DMG`):"—")}
function render(s){state=s;me=s.you;const p=mine(s);renderIdentity(p);renderScore(s,p);show(s.stage);if(s.stage==="lobby")renderLobby(s,p);if(s.stage==="countdown")$("countdown").textContent=s.countdown||"GO";if(s.stage==="race"&&p){$("raceId").textContent=`${names[p.slot]} OYUNCU`;$("raceStats").textContent=`Sıra: ${rank(s)}/${s.active} · İlerleme: ${p.position}/31`;$("turboText").textContent=p.turboTaps?`TURBO: sonraki ${p.turboTaps} dokunuş ×2`:""}if(s.stage==="result")renderResult(s);if(s.stage==="boss")renderBoss(s,p);if(s.stage==="boss_result")renderBossResult(s,p)}
function renderLobby(s,p){ready=!!p?.ready;$("roleText").textContent=!p?"İzleyici modundasın":p.waiting?"Beklemedesin; oyuna dönmek için aşağıdaki düğmeyi kullan":`${names[p.slot]} OYUNCU`;$("readyBtn").classList.toggle("hidden",!p||p.waiting);$("readyBtn").textContent=ready?"HAZIR ✓":"HAZIRIM";$("players").innerHTML=s.players.map(x=>`<div class="player"><span style="color:${colors[x.slot]}">Oyuncu ${x.slot+1}</span><strong>${x.waiting?"BEKLEMEDE":x.connected?(x.ready?"HAZIR":"BEKLİYOR"):"KOPTU"}</strong></div>`).join("");const can=p&&!p.waiting&&s.active>=2&&s.readyCount===s.active;$("startBtn").classList.toggle("hidden",!p||p.waiting);$("startBtn").classList.toggle("disabled",!can)}
function renderResult(s){const w=s.winner;$("winnerText").textContent=w===me?(s.newDeviceRecord?"YENİ REKOR!":"KAZANDIN!"):`OYUNCU ${w+1} KAZANDI`;$("scoreText").textContent=s.racesSinceBoss>=2?"Sırada King Boss seçimi var!":"Bir sonraki yarışa hazırlan"}
function renderBoss(s,p){const pct=s.bossMaxHp?Math.max(0,100*s.bossHp/s.bossMaxHp):0;$("hpFill").style.width=pct+"%";const isBoss=!!p&&p.slot===s.bossSlot;if(isBoss){$("bossTitle").textContent="👑 BOSS SENSİN";$("bossRole").textContent="Diğer oyunculara karşı dayan";$("bossAction").textContent="GÜÇ TOPLA!";$("bossHint").textContent="12 dokunuşta herkesi kısa süre durduran pulse";$("bossStats").textContent=`HP ${s.bossHp}/${s.bossMaxHp} · ${(s.bossRemainingMs/1000).toFixed(1)} sn · Enerji ${p.bossEnergy}/12`}else{$("bossTitle").textContent="BOSS’A KARŞI!";$("bossRole").textContent=s.bossSlot>=0?`${names[s.bossSlot]} oyuncu King Boss oldu`:"Boss seçiliyor";$("bossAction").textContent=p?.stunnedMs?"SERSEMLEDİN!":"SALDIR!";$("bossHint").textContent=p?.stunnedMs?`${(p.stunnedMs/1000).toFixed(1)} sn bekle`:"Telefonun tamamına dokun";$("bossStats").textContent=`HP ${s.bossHp}/${s.bossMaxHp} · ${(s.bossRemainingMs/1000).toFixed(1)} sn${p?` · Sen: ${p.bossDamage} hasar`:""}`}}
function renderBossResult(s,p){const isBoss=!!p&&p.slot===s.bossSlot;$("bossResultText").textContent=s.bossDefeated?(isBoss?"TAKIM SENİ YENDİ":"BOSS YENİLDİ!"):(isBoss?"KING BOSS KAZANDI!":"BOSS DAYANDI");$("bossResultScore").textContent=isBoss?`Boss olarak ${s.bossHp} HP ile tamamladın`:p?`Senin hasarın: ${p.bossDamage}${p.slot===s.topRaiderSlot?" · EN YÜKSEK HASAR!":""}`:"Boss turu tamamlandı"}
function tap(e){if(e?.cancelable)e.preventDefault();const n=Date.now();if(n-lastTap<45)return;lastTap=n;send("TAP");navigator.vibrate?.(8)}
$("matrixBtn").onpointerdown=e=>{e.preventDefault();send("SELECT_PLATFORM|matrix_8x32")};$("derbyBtn").onpointerdown=e=>{e.preventDefault();send("SELECT_GAME|pixel_derby")};$("readyBtn").onpointerdown=e=>{e.preventDefault();send("READY|"+(ready?0:1))};$("startBtn").onpointerdown=e=>{e.preventDefault();if(!e.currentTarget.classList.contains("disabled"))send("START")};$("rematchBtn").onpointerdown=e=>{e.preventDefault();send("REMATCH")};$("bossContinueBtn").onpointerdown=e=>{e.preventDefault();send("REMATCH")};$("waitBtn").onpointerdown=e=>{e.preventDefault();const p=mine(state);if(p)send(p.waiting?"WAIT|0":"WAIT|1")};$("leaveBtn").onpointerdown=e=>{e.preventDefault();send("LEAVE")};$("joinBtn").onpointerdown=e=>{e.preventDefault();send("HELLO|"+cid)};["race","boss"].forEach(id=>{const el=$(id);if(window.PointerEvent)el.addEventListener("pointerdown",tap,{passive:false});else{el.addEventListener("touchstart",tap,{passive:false});el.addEventListener("mousedown",tap,{passive:false})}});connect();
</script></body></html>
)HTML";
